services:
  nextjs:
    build: .
    ports:
      - 4200:3000
    volumes:
      - .:/home/node/app:cached
    environment:
      - NODE_ENV=development
    extra_hosts:
      - host.docker.internal:host-gateway
