services:
  golang:
    build: .
    ports:
      - 8080:8080
    environment:
      PARTNER_1_URL: http://host.docker.internal:8000/partner1
      PARTNER_2_URL: http://host.docker.internal:8000/partner2

    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - golang_mysql

  golang_mysql:
    image: mysql:8.0.39-debian
    container_name: golang_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets_db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
